<template>
  <!-- API documentation (Alex 2026-10-01: with a key but no route list, the AI "is running blind"). Generated by the
       API from its live routes (GET /me/api-docs), so it always matches what this account's key can call. -->
  <div class="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden">
    <div class="px-6 py-4 border-b border-gray-100 flex items-center gap-3">
      <div class="w-9 h-9 rounded-xl bg-primary-50 flex items-center justify-center shrink-0">
        <svg class="w-5 h-5 text-primary-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253" />
        </svg>
      </div>
      <div class="min-w-0">
        <h2 class="text-lg font-bold text-gray-900">{{ c.title }}</h2>
        <p class="text-xs text-gray-500">{{ docs ? c.count(docs.count) : c.subtitle }}</p>
      </div>
    </div>

    <div class="px-6 py-5 space-y-4">
      <p class="text-sm text-gray-600 leading-relaxed">{{ c.intro }}</p>

      <!-- The AI can read the docs itself with its key: one line to give it. -->
      <div class="rounded-xl border border-primary-200 bg-primary-50/60 px-4 py-3 space-y-2">
        <p class="text-xs font-bold text-primary-900">{{ c.tellAi }}</p>
        <code class="block bg-white border border-primary-200 rounded-lg px-3 py-2 text-xs font-mono text-gray-800 whitespace-pre-wrap break-all">{{ aiPrompt }}</code>
        <div class="flex flex-wrap gap-2">
          <button type="button" @click="copy(aiPrompt, 'prompt')" class="px-3 py-2 rounded-lg border border-primary-200 bg-white text-gray-700 hover:bg-gray-50 text-xs font-semibold">
            {{ copied === 'prompt' ? c.copied : c.copyPrompt }}
          </button>
          <button type="button" @click="copyMarkdown" :disabled="!docs" class="px-3 py-2 rounded-lg bg-primary-600 hover:bg-primary-700 text-white text-xs font-semibold disabled:opacity-50">
            {{ copied === 'md' ? c.copied : c.copyAll }}
          </button>
        </div>
      </div>

      <div v-if="loading" class="text-sm text-gray-500">{{ c.loading }}</div>
      <div v-else-if="!docs" class="text-sm text-red-600">{{ c.loadError }}</div>
      <template v-else>
        <input v-model="q" type="search" :placeholder="c.search" class="w-full rounded-xl border-gray-300 text-sm" />
        <div class="space-y-2">
          <details v-for="g in shown" :key="g.area" :open="!!q" class="rounded-xl border border-gray-100">
            <summary class="cursor-pointer px-3 py-2 text-sm font-semibold text-gray-800 flex items-center justify-between">
              <span class="font-mono">{{ g.area }}</span><span class="text-xs text-gray-400">{{ g.routes.length }}</span>
            </summary>
            <ul class="px-3 pb-3 space-y-2">
              <li v-for="(r, i) in g.routes" :key="i" class="text-xs">
                <div class="flex items-start gap-2">
                  <span :class="['shrink-0 w-14 text-center rounded px-1 py-0.5 font-bold', METHOD_CLS[r.method] || 'bg-gray-100 text-gray-700']">{{ r.method }}</span>
                  <code class="font-mono text-gray-900 break-all">{{ r.path }}</code>
                </div>
                <p class="mt-0.5 ml-16 text-gray-600">{{ r.summary }}</p>
                <p v-if="Object.keys(r.fields || {}).length" class="mt-0.5 ml-16 text-gray-500 break-words">
                  <span v-for="(rules, f) in r.fields" :key="f" class="mr-2"><code class="font-mono text-gray-800">{{ f }}</code><span v-if="rules" class="text-gray-400"> ({{ rules }})</span></span>
                </p>
              </li>
            </ul>
          </details>
          <p v-if="!shown.length" class="text-sm text-gray-500">{{ c.none }}</p>
        </div>
      </template>
    </div>
  </div>
</template>

<script setup>
const { $customFetch } = useNuxtApp()
const { language } = useLanguage()

const docs = ref(null)
const loading = ref(true)
const q = ref('')
const copied = ref(null)

const apiBase = computed(() => useRuntimeConfig().public.apiUrl || 'https://api.boxly.mx')
const aiPrompt = computed(() => (language.value === 'es'
  ? `Usa la API de Boxly con mi llave. Primero lee la documentación: GET ${apiBase.value}/me/api-docs?format=md con los encabezados "Authorization: Bearer <mi llave>" y "Accept: application/json".`
  : `Use the Boxly API with my key. First read the docs: GET ${apiBase.value}/me/api-docs?format=md with the headers "Authorization: Bearer <my key>" and "Accept: application/json".`))

const METHOD_CLS = {
  GET: 'bg-green-50 text-green-700', POST: 'bg-blue-50 text-blue-700', PUT: 'bg-amber-50 text-amber-700',
  PATCH: 'bg-amber-50 text-amber-700', DELETE: 'bg-red-50 text-red-700',
}

// A search matches the path, the summary or a field name; groups with no match drop out.
const shown = computed(() => {
  const term = q.value.trim().toLowerCase()
  const groups = docs.value?.groups || []
  if (!term) return groups
  return groups.map((g) => ({
    ...g,
    routes: g.routes.filter((r) => `${r.method} ${r.path} ${r.summary} ${Object.keys(r.fields || {}).join(' ')}`.toLowerCase().includes(term)),
  })).filter((g) => g.routes.length)
})

async function load() {
  loading.value = true
  try {
    const res = await $customFetch('/me/api-docs')
    docs.value = res?.data ?? null
  } catch (e) {
    console.error(e)
  } finally {
    loading.value = false
  }
}

async function copy(text, which) {
  try { await navigator.clipboard.writeText(text); copied.value = which; setTimeout(() => { if (copied.value === which) copied.value = null }, 2000) } catch { /* clipboard blocked */ }
}
async function copyMarkdown() {
  try {
    const md = await $customFetch('/me/api-docs', { query: { format: 'md' }, responseType: 'text' })
    await copy(String(md), 'md')
  } catch (e) { console.error(e) }
}

onMounted(load)

const T = {
  es: {
    title: 'Documentación de la API',
    subtitle: 'Las rutas que tu llave puede usar',
    count: (n) => `${n} rutas que tu llave puede usar`,
    intro: 'Todo lo que tu llave de API puede pedir, generado de la API en vivo. Dáselo a tu IA para que sepa qué rutas existen y qué datos lleva cada una.',
    tellAi: 'Dile esto a tu IA (ella lee la documentación sola con tu llave):',
    copyPrompt: 'Copiar instrucción',
    copyAll: 'Copiar documentación completa',
    copied: '¡Copiado!',
    loading: 'Cargando rutas…',
    loadError: 'No se pudo cargar la documentación.',
    search: 'Buscar ruta, acción o campo (p. ej. orders, refund, status)…',
    none: 'Ninguna ruta coincide.',
  },
  en: {
    title: 'API documentation',
    subtitle: 'The routes your key can call',
    count: (n) => `${n} routes your key can call`,
    intro: 'Everything your API key can ask for, generated from the live API. Give it to your AI so it knows which routes exist and what each one takes.',
    tellAi: 'Tell your AI this (it reads the docs itself with your key):',
    copyPrompt: 'Copy instruction',
    copyAll: 'Copy full documentation',
    copied: 'Copied!',
    loading: 'Loading routes…',
    loadError: 'Could not load the documentation.',
    search: 'Search a route, action or field (e.g. orders, refund, status)…',
    none: 'No route matches.',
  },
}
const c = computed(() => T[language.value] || T.es)
</script>
